name: Mon premier workflow Python

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Construire l'image Docker
        run: docker build -t mon-image-python .

      - name: Lancer le conteneur
        run: docker run --name test-container mon-image-python