name: Mon premier workflow Python

# 1. QUAND est-ce que le robot s'allume ?
on:
  push:
    branches: [ "main" ]  # Dès que tu envoies du code sur la branche main

# 2. QUE fait le robot ?
jobs:
  build-and-run:
    runs-on: ubuntu-latest  # Le robot utilise un ordinateur Linux (Ubuntu)

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4  # Le robot télécharge ton code

      - name: Construire l'image Docker
        run: docker build -t mon-image-python .

      - name: Lancer le conteneur
        run: docker run --name test-container mon-image-python